language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8 pytest pytest-cov tensorflow pyDOE
  - pip install . --no-cache-dir
script: travis_wait pytest --cov=pwlf -p no:warnings tests.py teststf.py
before_script:
  - flake8 pwlf
  - pytest --version
  - cd tests
after_success:
  - pip install python-coveralls
  - coveralls