language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8 pytest tensorflow pyDOE
  - pip install . --no-cache-dir
script: travis_wait pytest tests/tests.py tests/teststf.py
before_script: flake8 pwlf
